"""Second

Revision ID: 6d5aabfeef3e
Revises: ffbd1638569b
Create Date: 2020-06-16 21:42:02.053889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5aabfeef3e'
down_revision = 'ffbd1638569b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
