"""Update 1

Revision ID: f3b70cd7bb33
Revises: 2d4c974df65b
Create Date: 2020-06-16 21:50:20.315699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b70cd7bb33'
down_revision = '2d4c974df65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_column('asddd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asddd', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
